# This builds on the `base.pre-commit-config.yaml`. You can copy
# everything after the `repos:` line into your configuration file.
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
    - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.7'
    hooks:
    - id: bandit

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
        args:
          - "--check"
